# Numpy

In [1]:
import numpy as np
list1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(list1)
print(type(a))
print(a.ndim, a.shape)

<class 'numpy.ndarray'>
1 (10,)


In [2]:
b = np.array([[1,2,3,],[4,5,6,]])
print(a.ndim, b.shape)
print(b[0,0])

1 (2, 3)
1


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape) 
print(b[0,0])

(2, 3)
1


In [4]:
d = np.array([[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]],
[[11, 12, 13, 14],
[15, 16, 17, 18],
[19, 20, 21, 22]]])
print(len(d))
print(len(d[0]))
print(len(d[0][0]))
print(d.ndim)
print(d.shape)

2
3
4
3
(2, 3, 4)


In [5]:
import numpy as np
lst = [
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
]
a = np.array(lst)
print(a[0, 1])
print(a[2,3]) 
print(a[[0, 1], [2, 3]])

2
12
[3 8]


In [6]:
import numpy as np
lst = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
arr = np.array(lst)
#print(arr)
print(arr[0, :]) # 첫번째 행 전체
print(arr[:, 1]) # 두번째 열 전체
print(arr[1, 1:]) # 두번째 행의 두번째 열부터 끝열까지
print(arr[:2, :2])

[1 2 3]
[2 5 8]
[5 6]
[[1 2]
 [4 5]]


In [7]:
import numpy as np
lst = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
a = np.array(lst) 
bool_indexing_array = np.array([
[False, True, False],
[True, False, True],
[False, True, False]
])
n = a[bool_indexing_array];
print(n) 


[2 4 6 8]


In [8]:
    
import numpy as np
lst = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
a = np.array(lst) 
# 배열 a 에 대해 짝수면 True, 홀수면 False 
bool_indexing = (a % 2 == 0) 
print(bool_indexing)
# 부울린 인덱스를 사용하여 True인 요소만 뽑아냄
print(a[bool_indexing]) 
# 더 간단한 표현
n = a[ a % 2 == 0 ]
print(n)

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]


In [9]:
import numpy as np
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
print( a[idx] ) 
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
print( a[idx] ) 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[:, [True, False, False, True]])
print(a[[2, 0, 1], :] )

[11 33 55 77 99]
[11 11 11 11 11 11 22 22 22 22 22 33 33 33 33 33]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [10]:
import numpy as np
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]
    z[:10]

UsageError: Line magic function `%%time` not found.


In [11]:
%%time
z = x + y
z[:10]

Wall time: 0 ns


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6]) 
c = a + b # 각 요소 더하기
# c = np.add(a, b)
print(c) # [5 7 9] 
c = a - b # 각 요소 빼기
# c = np.subtract(a, b)
print(c) # [-3 -3 -3] 
# c = a * b # 각 요소 곱하기
c = np.multiply(a, b)
print(c) # [4 10 18]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [13]:
# c = a / b # 각 요소 나누기
c = np.divide(a, b)
print(c) # [0.25 0.4 0.5] 
print(a == 2)
print(b > 5 )
print((a == 2) & (b > 5))
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.all(a == b)
np.all(a == c)

[0.25 0.4  0.5 ]
[False  True False]
[False False  True]
[False False False]


True

In [14]:
import numpy as np

a=np.array([[1,2], [3,4]])
b=np.array([[5,6], [7,8]])

c=np.dot(a,b)
print(c)

a=np.arange(5)
print(np.exp(a))
print(10**a)
print(np.log(a+1))

[[19 22]
 [43 50]]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[    1    10   100  1000 10000]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
import numpy as np
a=np.array([[1,2], [3,4]])

s=np.sum(a)
print(s)

s=np.sum(a, axis=0)
print(s)

s=np.sum(a, axis=1)
print(s)

s=np.prod(a)
print(s)

10
[4 6]
[3 7]
24


In [16]:
import numpy as np

print(np.all([True, True, False]))
print(np.any([True, True, False]))

a = np.zeros((100, 100), dtype=np.int)
print(np.any(a!=0))
print(np.all(a==a))

a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
print( ((a <=b) & (b <=c)).all())

False
True
False
True
True


In [17]:
import numpy as np
x = np.array([[1, 1], [2, 2]])
print( x.sum() )
print( x.sum(axis=0)) # 열 합계
print( x.sum(axis=1)) # 행 합계

6
[3 3]
[2 4]


In [18]:
import numpy as np

x=np.array([1,2,3,])
print(x.dtype)

x=np.array([1.0, 2.0, 3.0])
print(x.dtype)

x=np.array([1, 2, 3.0])
print(x.dtype)

x=np.array([1,2,3], dtype='f')
print(x.dtype)
print(x[0] + x[1])

x=np.array([1,2,3], dtype='U')
print(x.dtype)
print(x[0] + x[1])

int32
float64
float64
float32
3.0
<U1
12


In [19]:
print(np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0]))
print(np.log(0))
print(np.exp(-np.inf))

[  0.  inf -inf  nan]
-inf
0.0


C:\Users\korha\anaconda3\envs\basic\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\korha\anaconda3\envs\basic\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\korha\anaconda3\envs\basic\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [20]:
import numpy as np

a=np.zeros(5)
print(a)
a=np.zeros((2,2))
print(a)

a=np.zeros((5,2), dtype='i')
print(a)

a=np.zeros(5, dtype='U4')
print(a)

a[0] = 'abc'
a[1] = 'abcd'
a[2] = 'ABCDE'
print(a)



[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
['' '' '' '' '']
['abc' 'abcd' 'ABCD' '' '']


In [21]:
import numpy as np

a = np.full((2,3), 5)
print(a) 
a = np.eye(3)
print(a) 
a = np.array(range(20)).reshape((4,5))
print(a)
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수
np.logspace(0.1, 1, 10)

[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [22]:
import numpy as np
a = np.arange(12)
print(a.shape)
b = a.reshape(3, 4)
print( b )
print(b.shape)

print(a.reshape(4, -1) )

print(a.reshape(2, 2, -1) )

print( a.reshape(2, -1, 2) )

print(a.flatten())
print(a.shape)

x = np.arange(5)
print( x )

print( x.reshape(1, 5))


print( x.reshape(5, 1))

print(x[:, np.newaxis])

print(x.shape)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[0 1 2 3 4]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
(5,)


In [24]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

print(np.median(x))
print(np.percentile(x,0))
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))
print(np.percentile(x,100))

5.0
-24.0
0.0
5.0
10.0
23.0


In [25]:
import numpy as np
np.random.seed(0)
print( np.random.rand(5) )
print( np.random.rand(10) )
print( np.random.rand(10) )
np.random.seed(0)
print( np.random.rand(5) )
print( np.random.rand(10) )
print( np.random.rand(10) )


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152 0.79172504
 0.52889492 0.56804456 0.92559664 0.07103606]
[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215 0.97861834
 0.79915856 0.46147936 0.78052918 0.11827443]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152 0.79172504
 0.52889492 0.56804456 0.92559664 0.07103606]
[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215 0.97861834
 0.79915856 0.46147936 0.78052918 0.11827443]


In [26]:
import numpy as np
print( np.random.choice(5, 5, replace=False) ) # shuffle 명령과 같다. print( np.random.choice(5, 3, replace=False) ) # 3개만 선택
print( np.random.choice(5, 10) ) # 반복해서 10개 선택
print( np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) ) # 선택 확률을 다르게 해서 10개 선택

[4 2 3 1 0]
[0 2 4 3 3 2 4 2 0 0]
[2 2 2 2 3 3 3 3 0 3]


In [27]:
import numpy as np
print(np.random.randint(10, size=10))
print(np.random.randint(10,20,size=10))
print(np.random.randint(10,20,size=(3,5)))

[6 7 2 0 3 5 9 4 4 6]
[14 14 13 14 14 18 14 13 17 15]
[[15 10 11 15 19]
 [13 10 15 10 11]
 [12 14 12 10 13]]


In [106]:
import numpy as np
print(np.random.randint(2, size=10)) #동전

dice = np.random.randint(1, 7, size=100) #주사위
print(np.mean(dice))

stock = 10000+(10000 * (np.random.randn(250)/100)) #주식
print(stock)
print(len(stock))

[0 1 0 0 1 1 0 0 0 1]
3.66
[ 9798.35933722  9946.05453666  9972.43294654  9929.02720342
 10173.88726775 10099.43943913 10131.91368763  9911.75811815
 10112.85940645 10049.60009463 10077.14059487 10102.94388288
  9909.1236754   9957.5682379  10086.25960113  9734.4380907
 10151.33280826 10055.31320642  9995.42960393 10022.05076558
  9897.00647167  9965.00566354 10110.02843382 10129.80219723
 10269.62240526  9992.60753337  9934.14470332  9948.57660341
  9898.19581247  9992.21452441 10038.273243    9996.57577195
 10109.63468457  9976.57841987  9965.25493475  9941.87315231
  9836.73654738  9843.22322757  9882.08420694 10130.14280717
 10089.52602729 10137.49640664  9866.77883454  9803.13753102
  9933.99436799 10017.58189533 10049.86902749 10104.7972156
 10028.42796708 10174.26687807  9977.73943191  9908.6920782
  9831.87817845  9911.10286419 10024.2117961   9911.12797426
 10093.67424635 10141.2327706   9763.04130948 10086.40523005
  9776.03959413 10040.14990551 10122.48705642 10006.48561063


In [28]:
import numpy as np

print(np.unique([11, 11, 2, 2, 34, 34]))
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)
print(index)
print(count)
print(np.bincount([1,1,2,2,2,3], minlength=6))

[ 2 11 34]
['a' 'b' 'c']
[2 2 1]
[0 2 3 1 0 0]


# Pandas

In [31]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2466052],
index=["서울", "부산", "인천", "대구"])
print( s )
print( pd.Series(range(10, 14)) )
print( s.index )
print( s.values )
s.name = "인구" 
s.index.name = "도시" 
print( s )


서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64
0    10
1    11
2    12
3    13
dtype: int64
Index(['서울', '부산', '인천', '대구'], dtype='object')
[9904312 3448737 2890451 2466052]
도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [32]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2466052],
index=["서울", "부산", "인천", "대구"])
print(s / 1000000)

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64


In [33]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
print( s0 )
print( s0.a )
print( s0.b )

a    0
b    1
c    2
dtype: int64
0
1


In [34]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2466052],
index=["서울", "부산", "인천", "대구"])
print( s[1], s["부산"] )
print( s[3], s["대구"] )
print( s[[0, 3, 1]] )
print( s[["서울", "대구", "부산"]] )
print( s[(250e4 < s) & (s < 500e4)] ) # 인구가 250만 초과, 500만 미만인 경우
s["부산":"대구"] # 부산에서 대구까지 (대구도 포함)
s0 = pd.Series(range(3), index=["a", "b", "c"])
print( s0 )
print( s0.a )
print( s0.b )

3448737 3448737
2466052 2466052
서울    9904312
대구    2466052
부산    3448737
dtype: int64
서울    9904312
대구    2466052
부산    3448737
dtype: int64
부산    3448737
인천    2890451
dtype: int64
a    0
b    1
c    2
dtype: int64
0
1


In [35]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
print("서울" in s) # 인덱스 라벨 중에 서울이 있는가
print("대전" in s) # 인덱스 라벨 중에 대전이 있는가
for k, v in s.items():
    print("%s = %d" % (k, v))


True
False
서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [36]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
ds = s-s2
print(ds)
#NaN 값이 float 자료형에서만 가능하므로 다른 계산 결과도 모두 float 자료형이 되었다
print(s.values - s2.values)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64
[272830  55546 258416 975894]


In [37]:
print(ds.notnull())
print(ds[ds.notnull()])
rs = (s-s2) / s2*100
print(rs)
rs = rs[rs.notnull()]
print(rs)

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64
대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [38]:
rs["부산"] = 1.63
print(rs)
rs["대구"] = 1.41
print(rs)
del rs["서울"]
print(rs)

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64
부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64
부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64


In [39]:
import pandas as pd
data = {
"2015": [9904312, 3448737, 2890451, 2466052],
"2010": [9631482, 3393191, 2632035, 2431774],
"2005": [9762546, 3512547, 2517680, 2456016],
"2000": [9853972, 3655437, 2466338, 2473990], "지역": ["수도권", "경상권", "수도권", "경상권"],
"2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141] }
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]

df = pd.DataFrame(data, index=index, columns=columns)
#print(df.columns)
#print(df.values)
#print(df.columns)
#print(df.index)
df.index.name = "도시"
df.columns.name = "특성"
print(df)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141


In [40]:
import pandas as pd
print( df.T )

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141


In [41]:
# "2010-2015 증가율"이라는 이름의 열 추가
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
print(df)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41


In [42]:
# "2005-2010 증가율"이라는 이름의 열 추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
print(df)


특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99


In [43]:
# "2010-2015 증가율"이라는 이름의 열 삭제
del df["2010-2015 증가율"]
print(df)

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99


In [44]:
import pandas as pd
# 하나의 열만 인덱싱하면 시리즈가 반환된다. 
D1 = df["지역"]
print(D1) ; print(type(D1))

#여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
print(df[["2010", "2015"]])

#2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
print(df[["2010"]])

print(type(df[["2010"]]))

#2010이라는 열을 반환하면서 시리즈 자료형으로 반환
print(df["2010"])

#print(df[0])

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object
<class 'pandas.core.series.Series'>
특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052
특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774
<class 'pandas.core.frame.DataFrame'>
도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64


In [45]:
import numpy as np
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
print(df2)
print(df2[2])
print(df2[[1,2]])

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
0     2
1     6
2    10
Name: 2, dtype: int32
   1   2
0  1   2
1  5   6
2  9  10


In [46]:
import pandas as pd
print(df[:1])

print(df[1:2])

print(df[1:3])

print(df["서울":"부산"])

print(df["2015"]["서울"])

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4
특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
9904312


In [47]:
import pandas as pd

data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

print(df)

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70


In [48]:
#(1)
s = pd.Series([90, 60, 80, 70], index = ["춘향", "몽룡","향단", "방자"])
print(s)

춘향    90
몽룡    60
향단    80
방자    70
dtype: int64


In [49]:
#(2)
df = pd.DataFrame(data, index= index, columns=columns)
print(df[["국어", "영어"]])

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40


In [51]:
import pandas as pd

dict_data = {'a':1,'b':2,'c':3}
series_data = pd.Series(dict_data)

print(type(series_data))
print('\n')
print(series_data)

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64
